config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(todo_params)
    redirect_to todo_path(@todo.id)
  end

  def edit
    @todo = Todo.find(params[:id])
  end
    
  def update
    @todo = Todo.find(params[:id])
    @todo.update todo_params
    redirect_to todo_path(@todo)
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to root_path
  end

  private
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= form_for @todo do |f| %>

  <%= label_tag :title, "Title:" %>
  <%= f.text_field :title %>

  <%= label_tag :description, "description:" %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1>Index</h1>
<ul>
  <% @todos.each do |todo| %>
    <li>
      <%= link_to todo.title, todo %>
      <%= link_to "edit", edit_todo_path(todo.id) %>
      <%= link_to "destroy", todo, method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to "Create new todo", new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= form_for @todo do |f| %>

  <%= label_tag :title, "Title:" %>
  <%= f.text_field :title %>

  <%= label_tag :description, "Description:" %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Show Todo</h1>
<p>Title: <%= @todo.title %></p>
<p>Description: <%= @todo.description %></p>

<%= link_to "Back to Home", root_path %>